development:
  adapter: postgresql
  database: McWilliamsStores
  username: steven
  host: localhost

test:
  adapter: postgresql
  database: McWilliamsStoresTest
  username: steven
  host: localhost
