development:
  adapter: postgresql
  database: McWilliamsStores
  username: tristan
  host: localhost

test:
  adapter: postgresql
  database: McWilliamsStoresTest
  username: tristan
  host: localhost
