development:
  adapter: postgresql
  database: TasteTheDifference
  username: steven
  host: localhost
  template: template0

test:
  adapter: postgresql
  database: TasteTheDifferenceTest
  username: steven
  host: localhost
  template: template0
